name: Translate resume files

on:
  push:
    paths:
      - 'resume.i18n.json'

  workflow_dispatch:

jobs:
  generate-resume:
    runs-on: ubuntu-latest
    env:
      THEME_NAME: 'ludoo'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Translate resume files
        run: |
          node .github/scripts/split-languages.js --action=split

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add resume.en.json resume.fr.json
          git commit -m "chore: update language-specific resume files" || exit 0
          git push

      # Update gist resume.json : https://gist.github.com/ludoo0d0a/b7e4355cd0d2722f25002eca525ea262
      # to see changes into jsonresume.org website : https://registry.jsonresume.org/ludoo0d0a
      - name: Update Gist
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        if: ${{ env.GIST_ID != '' }}
        run: |
          gh gist edit $GIST_ID -f resume.json resume.en.json

      - name: Install
        run: |
          npm install -g resume-cli
          npm install jsonresume-theme-${{ env.THEME_NAME }}

      - name: Generate output files
        run: |
          node .github/scripts/split-languages.js --action=generate --theme=${{ env.THEME_NAME }} --langs=${{ env.LANGUAGES }}

      - name: ls
        run: |
          ls

      - name: ls pdf
        run: |
          ls pdf

      - name: Homepage index.html
        run: |
          cp index-en.html index.html

      - name: Commit generated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pdf/*.pdf index.html index-*.html
          git commit -m "chore: generated files" || exit 0
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages

      - name: Log Deploy URL
        run: |
          echo "::notice::Resume deployed to https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

